name: CI - Main Workflow

on:
  pull_request:
    types: [opened, synchronize]

  workflow_dispatch:

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Linter
        run: npm run lint
